apiVersion: v1
kind: Endpoints
metadata:
  name: {{service_name}}
  namespace: {{namespace}}
subsets:
  - addresses:
      - ip: 10.0.0.1
    ports:
      - port: 80
        name: http
        protocol: TCP
        