apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding # Alternatively, you can use ClusterRoleBinding for cluster-wide permissions
metadata:
  name: {{rolebinding_name}}
  namespace: {{namespace}} # Not needed for ClusterRoleBinding
subjects:
- kind: ServiceAccount
  name: {{serviceaccount_name}}
  namespace: {{namespace}}
roleRef:
  kind: Role
  name: {{role_name}}
  apiGroup: rbac.authorization.k8s.io