# Docker Registry Secret Example
apiVersion: v1
kind: Secret
metadata:
  name: {{secret_name}}
  namespace: {{namespace}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{base64_encoded_docker_config}} # Docker Config Example

---

# Opaque Secret Example
apiVersion: v1
kind: Secret
metadata:
  name: {{opaque_secret_name}}
  namespace: {{namespace}}
type: Opaque
data:
  username: {{base64_encoded_username}} # Example: echo -n 'username' | base64
  password: {{base64_encoded_password}} # Example: echo -n 'password' | base64

---

# TLS Secret Example
apiVersion: v1
kind: Secret
metadata:
  name: {{tls_secret_name}}
  namespace: {{namespace}}
type: kubernetes.io/tls
data:
  tls.crt: {{base64_encoded_tls_certificate}} # Example: cat tls.crt | base64 -w 0
  tls.key: {{base64_encoded_tls_key}}         # Example: cat tls.key | base64 -w 0

---

# Basic Authentication Secret Example
apiVersion: v1
kind: Secret
metadata:
  name: {{basic_auth_secret_name}}
  namespace: {{namespace}}
type: Opaque
data:
  .htpasswd: {{base64_encoded_htpasswd}} # Example: htpasswd -nb user password | base64

---

# SSH Key Secret Example
apiVersion: v1
kind: Secret
metadata:
  name: {{ssh_secret_name}}
  namespace: {{namespace}}
type: Opaque
data:
  ssh-privatekey: {{base64_encoded_ssh_private_key}} # Example: cat id_rsa | base64 -w 0
  ssh-publickey: {{base64_encoded_ssh_public_key}}   # Example: cat id_rsa.pub | base64 -w 0