apiVersion: v1
kind: Pod
metadata:
  name: {{pod_name}}
  namespace: {{namespace}}
  labels:
    app: {{app_label}}
  annotations:
    description: "Advanced pod with initContainers, ephemeralContainers, probes, and resource limits"
spec:
  nodeSelector:
    disktype: ssd
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - {{app_label}}
        topologyKey: "kubernetes.io/hostname"
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 50
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - {{app_label}}
          topologyKey: "failure-domain.beta.kubernetes.io/zone"
  tolerations:
  - key: "key"
    operator: "Equal"
    value: "value"
    effect: "NoSchedule"
  initContainers:
  - name: init-container
    image: busybox:latest
    command: ["sh", "-c", "echo Initializing..."]
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"
  containers:
  - name: main-container
    image: {{image}}
    command: ["{{cmd}}"]
    args: ["{{arg1}}", "{{arg2}}"]
    ports:
    - containerPort: {{container_port}}
      protocol: TCP
    env:
    - name: ENV_VAR
      value: "value"
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    volumeMounts:
    - name: config
      mountPath: /etc/config
    livenessProbe:
      httpGet:
        path: /healthz
        port: {{container_port}}
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /ready
        port: {{container_port}}
      initialDelaySeconds: 5
      periodSeconds: 5
    startupProbe:
      exec:
        command: ["/bin/check-startup"]
      failureThreshold: 30
      periodSeconds: 10
  ephemeralContainers:
  - name: debug-container
    image: busybox:latest
    command: ["sh"]
  volumes:
  - name: config
    configMap:
      name: {{configmap_name}}