apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{statefulset_name}}
  namespace: {{namespace}}
  labels:
    app: {{app_label}}
spec:
  serviceName: "{{headless_service_name}}"
  replicas: {{replica_count}}
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  selector:
    matchLabels:
      app: {{app_label}}
  template:
    metadata:
      labels:
        app: {{app_label}}
    spec:
      containers:
      - name: {{container_name}}
        image: {{image}}
        ports:
        - containerPort: {{container_port}}
        volumeMounts:
        - name: data
          mountPath: /var/lib/{{app_label}}
          subPath: data
        env:
        - name: ENV_VAR
          value: "value"
        livenessProbe:
          tcpSocket:
            port: {{container_port}}
          initialDelaySeconds: 30
          periodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.beta.kubernetes.io/storage-class: "{{storage_class}}"
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{storage_size}}