apiVersion: v1
kind: Pod
metadata:
  name: {{pod_name}}-volumes
  namespace: {{namespace}}
spec:
  containers:
  - name: app
    image: {{image}}
    volumeMounts:
    - name: emptydir-volume
      mountPath: /tmp/emptydir
    - name: configmap-volume
      mountPath: /etc/config
    - name: secret-volume
      mountPath: /etc/secret
    - name: hostpath-volume
      mountPath: /mnt/data
  volumes:
  - name: emptydir-volume
    emptyDir: {}
  - name: configmap-volume
    configMap:
      name: {{configmap_name}}
  - name: secret-volume
    secret:
      secretName: {{secret_name}}
  - name: hostpath-volume
    hostPath:
      path: /mnt/data
      type: Directory