apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{pv_name}}
spec:
  capacity:
    storage: {{storage_size}}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{storage_class}}
  csi:
    driver: {{csi_driver}}
    volumeHandle: {{volume_handle}}
    fsType: ext4
    volumeAttributes:
      device: {{device_path}}