apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{storage_class}}
provisioner: {{provisioner}}
parameters:
  type: {{disk_type}}
  fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer