apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ .Release.Name }}-snapshot
spec:
  volumeSnapshotClassName: {{ .Values.snapshotClass }}
  source:
    persistentVolumeClaimName: {{ .Release.Name }}-pvc
