apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler-{{node_name}}
  namespace: kube-system
  labels:
    component: kube-scheduler
    tier: control-plane
spec:
  hostNetwork: true
  priorityClassName: system-node-critical
  containers:
  - name: kube-scheduler
    image: k8s.gcr.io/kube-scheduler:{{k8s_version}}
    command:
      - kube-scheduler
      - --address=127.0.0.1
      - --kubeconfig=/etc/kubernetes/scheduler.conf
      - --leader-elect=true
      - --policy-configmap={{scheduler_policy_configmap}}
      - --v=2
    volumeMounts:
    - name: config
      mountPath: /etc/kubernetes
      readOnly: true
  volumes:
  - name: config
    hostPath:
      path: /etc/kubernetes