apiVersion: v1
kind: Pod
metadata:
  name: cloud-controller-manager-{{node_name}}
  namespace: kube-system
  labels:
    component: cloud-controller-manager
    tier: control-plane
spec:
  hostNetwork: true
  priorityClassName: system-cluster-critical
  containers:
  - name: cloud-controller-manager
    image: k8s.gcr.io/cloud-controller-manager:{{ccm_version}}
    command:
      - cloud-controller-manager
      - --kubeconfig=/etc/kubernetes/cloud-controller-manager.conf
      - --leader-elect=true
      - --v=2
      - --allocate-node-cidrs={{allocate_node_cidrs}}
    volumeMounts:
    - name: config
      mountPath: /etc/kubernetes
      readOnly: true
    - name: certs
      mountPath: /etc/kubernetes/pki
      readOnly: true
  volumes:
  - name: config
    hostPath:
      path: /etc/kubernetes
  - name: certs
    hostPath:
      path: /etc/kubernetes/pki