apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: {{app_name}}
build:
  artifacts:
  - image: {{image}}
deploy:
  kubectl:
    manifests:
      - k8s-manifests/*.yaml
profiles:
- name: minikube
  activation:
    - kubeContext: minikube
  build:
    local:
      push: false