apiVersion: v1
kind: LimitRange
metadata:
  name: {{limitrange_name}}
  namespace: {{namespace}}
spec:
  limits:
  - type: Container
    max:
      cpu: "2"
      memory: "1Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    default:
      cpu: "500m"
      memory: "256Mi"
    defaultRequest:
      cpu: "250m"
      memory: "256Mi"