apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.mygroup.mydomain
spec:
  service:
    name: my-apiserver
    namespace: my-namespace
  group: mygroup.mydomain
  version: v1
  insecureSkipTLSVerify: true
