apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{app_name}}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/{{user}}/{{repo}}.git'
    targetRevision: HEAD
    path: {{app_path}}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{namespace}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true