apiVersion: v1
kind: Service
metadata:
  name: {{service_name}}
  namespace: {{namespace}}
  labels:
    app: {{app_label}}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
spec:
  type: {{service_type}}  # Options: ClusterIP, NodePort, LoadBalancer
  sessionAffinity: ClientIP
  externalTrafficPolicy: Local
  ports:
  - name: http
    protocol: TCP
    port: {{port}}
    targetPort: {{target_port}}
  selector:
    app: {{app_label}}