apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ingress_name}}
  namespace: {{namespace}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - {{hostname}}
    secretName: {{tls_secret}}
  rules:
  - host: {{hostname}}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{service_name}}
            port:
              number: {{port}}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{service_name}}
            port:
              number: {{port}}