apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{rs_name}}
  namespace: {{namespace}}
spec:
  replicas: {{replicas}}
  selector:
    matchLabels:
      app: {{app_label}}
  template:
    metadata:
      labels:
        app: {{app_label}}
    spec:
      containers:
        - name: {{container_name}}
          image: {{image}}
